### ISSUE TITLE
Any strategies to speed up search time?

### ISSUE THREAD

**Issue by dvdmrn** [OrganicIrradiation/scholarly#11]
Sorry this may not be the best place to post this but it takes a good 10-15 seconds to retrieve results when calling `search_pubs_query()`. Is there any way to speed this up? (e.g. specify to only retrieve the first n results or something to that effect)

edit: it seems to also take a very long time to simply go `next(generator_object_of_pubs).fill()`

**Comment by sandeepjoshiaw** [comment]
I think its slow to make sure you're not blocked by Google Scholar for
repetitive requests. I haven't looked at the source code but that's my best
guess.

**Comment by OrganicIrradiation** [comment]
The requests are slowed in ```_get_page``` to minimize load on the Google Scholar servers so that the script is not blocked as a bot. However, overuse will still trigger a 503 Service Unavailable error, which is a captcha request (and not currently handled by scholarly). The only way to use it after a block is to either solve the captcha or wait.

**Comment by OrganicIrradiation** [comment]
Unless there are recommendations for handling server request handling, I'm going to close this issue.
