### ISSUE TITLE
fill() is returning TypeError!

### ISSUE THREAD

**Issue by nalbishry** [OrganicIrradiation/scholarly#54]
Hi there,
I've been trying to follow the search_author example as shown.
```
results = scholarly.search_author('Steven A Cholewiak')
author = next(results).fill()
```
it keeps throwing:
`TypeError: 'unicode' object is not callable`

any help would be really appreciated
Thanks

**Comment by garne041** [comment]
I just downloaded this package and I came across this too. I included my solution at the bottom.

You may have noticed that on your local machine there was an extra u' in front of all of the search_query results. However, that doesn't happen in the tutorials on the main webpage.

For example:
Bad encoding
>>> search_query = scholarly.search_author('Steven A Cholewiak')
>>> print(next(search_query))
{'_filled': False,
 'affiliation': u'Assistant Project Scientist, University of California, Berkeley',
 'citedby': 235,
 'email': u'@berkeley.edu',
 'id': u'4bahYMkAAAAJ',
 'interests': [u'Depth Cues',
               u'3D Shape',
               u'Shape from Texture & Shading',
               u'Naive Physics',
               u'Haptics'],
 'name': u'Steven A. Cholewiak',
 'url_picture': u'https://scholar.google.com/citations?view_op=medium_photo&user=4bahYMkAAAAJ'}

With correct encoding, this is supposed to be
>>> print(next(scholarly.search_author('Steven A. Cholewiak')))
{'_filled': False,
 'affiliation': 'Assistant Project Scientist, University of California, '
                'Berkeley',
 'citedby': 235,
 'email': '@berkeley.edu',
 'id': '4bahYMkAAAAJ',
 'interests': ['Depth Cues',
               '3D Shape',
               'Shape from Texture & Shading',
               'Naive Physics',
               'Haptics'],
 'name': 'Steven A. Cholewiak',
 'url_picture': 'https://scholar.google.com/citations?view_op=medium_photo&user=4bahYMkAAAAJ'}


 Apparently, it may have been an encoding issue (utf-8) preventing the Author.fill() to search correctly.

What I did to solve it on my end was to 
(1) move from using Python 2.7 to Python 3.6 and 
(2) re-installing scholarly with `pip3 install scholarly` instead of `pip install scholarly`. 

That cleared it up for me. Now it works fine for me.
