### ISSUE TITLE
Backlog of pull requests

### ISSUE THREAD

**Issue by bielsnohr** [OrganicIrradiation/scholarly#77]
I was about to make a pull request from my fork https://github.com/bielsnohr/scholarly, but then I checked the pending pull requests on this repository and realised that there is a large backlog. A good number are close to being 1 year old, and there hasn't been any activity from the owner for nearly the same amount of time.

The number of pull requests with useful features suggests that there is quite an active community that could support and improve this package a great deal, but it seems to me everything is being held back by an absent maintainer. Not an accusation or criticism, just the reality of the situation. Life happens.

I'm wondering what the best way to rectify this would be. Create a new fork hosted by one of the more active contributors and then transfer PyPI to point at that one? Or is it possible to get more contributors with write access on this repository?

**Comment by OrganicIrradiation** [comment]
Very true statement: Life happens.

I haven't had time to directly address the backlog and due to relatively recent life events can't be involved in the development. I'm happy to add collaborators who are able to make meaningful contributions.

**Comment by silvavn** [comment]
I would like to be a collaborator if possible. Me and @janruh have been developing many features for this package during the last few months.

**Comment by bielsnohr** [comment]
Thank you @OrganicIrradiation for opening up the repository to more collaborators. We have doubtless all had the experience of lacking time to invest in certain activities when other ones demand all our attention. It is the very reason software packages supported by a community tend to last longer, so that load can be shared.

@silvavn and @ipeirotis I think we should discuss a strategy for clearing the backlog to avoid a "Wild West" situation and end up with a disjointed and broken package. In my opinion, creating a more robust testing suite should be our priority because this will give us confidence to make a lot of changes quickly and prevent any regressions. 

As it stands, the unittest module for this package is too dependent on dynamic data in Google Scholar. The number of authors/publications for particular queries is constantly changing, meaning the static tests become out of date quickly and therefore don't accurately test scholarly. Pull request #60 partially addresses this with a `>=` assertion, and although I do like the originality, I don't think it is a complete solution. Perhaps the tests should be based on data in Google Scholar that is a bit more static (e.g. deceased authors that are no longer publishing)? However, even with this it is unlikely we will be able to escape the following workflow for testing pull requests: 

1. Receive pull request from fork "A"
2. Update tests with numbers from current master
3. Commit test changes to master
4. Merge test changes into fork A. Not sure how that would work in practice, perhaps a "develop" branch like in GitFlow? We could be more loose about merging into the develop branch, and then check that the updated tests pass on that branch before doing a subsequent merge to master. However, this sort of thing should also be possible with pull requests that allow for additional commits to be added after the pull request is made.
5. Merge pull request if tests pass and after other review

If I have time this week, I'll see if I can hatch something to address at least some of this. We should also consider getting some automation into the testing with the likes of Travis CI or Circle CI.

Interested to hear thoughts about all of this.

**Comment by silvavn** [comment]
I totally agree. 
I think that after the merges, the first thing should be defining the features and purpose that the package should have.

As for the test, since this is a webcrawler, there is no guarantee that the data will not change. I would suggest that we download a set of pages and make them a standard test set. If things change drastically then we can rework the tests around the new scenario.

As for development, I really dislike that after a couple requests we get blocked out of scholar. So I think including selenium or re-routing through VPNs should be a development goal.

**Comment by ipeirotis** [comment]
For the issue of blocking, I found the use of Tor to alleviate significantly any issues. You can achieve the same effect with a list of proxies, but I found that proxies tend to be blocked significantly more often than Tor. (The `use_proxy` command was a piece of code contributed by my team.)

For testing, I think that having a "larger than" check, together with a "publication exists" test will be more than sufficient for most purposes. If we see things passing these tests but still failing in practice, we can reassess.

Towards better testing, I would also recommend having a CI/CD framework, with a nightly build/test. In that case, we can get notifications quickly if a test started failing.

**Comment by silvavn** [comment]
I agree with @ipeirotis we have an implementation that uses TOR and works both with selenium and beautifulsoup (selenium blocks even less since it randomises user agents etc, etc.) in a fork that was started by @janruh and extended by myself.

**Comment by janruh** [comment]
I would suggest merging my fork, testing the support for Linux (with my original code it worked on Linux) and moving on from there.

**Comment by bielsnohr** [comment]
Great to see a number of pull requests cleared. A few additional comments:

1. I have created a `develop` branch in this repo. In the style of gitflow, I propose it should be used for merging from forks (and more generally). That way we can fully test any major changes without breaking `master`. Thoughts?
2. For the testing suite, I have come to agree with @ipeirotis that it will be sufficient to implement "greater than" and "publication exists" tests for the moment. I believe there are now two pull requests that now have these features. However, these tests are susceptible to error if _more_ publications are being returned than should be. In the long run, I do like @silvavn 's idea of downloading some static pages and using those to provide deterministic results. I will split that out into a separate issue.
3. @janruh and @silvavn I have taken a quick look at your collaborative pull request #76 . Lots of good looking features, but it is also quite a hefty refactor of the existing code. I don't have as much experience with managing that sort of pull request, so it would be good to talk about how we proceed. In particular, how this will overlap/interact with the recent pull requests related to using proxies. Perhaps best to move conversation to that pull request.

**Comment by ipeirotis** [comment]
I have taken a pass.

a. I created a CI process using GitHub Actions. When someone issues a PR against the `develop` and the `master` branches, the process runs a flake8 test, plus the test suite.

b. The workflow process installs Tor, and runs the tests using Tor as a proxy. I also tried with using FreeProxies but it was failing way too often, even with a continuous resetting of the proxies. However, with Tor things seem to run _relatively_ smoothly. 

c. I updated the test suite to avoid the explicit use of the `next` command, and instead rely on comprehensions to extract the list of results. I made also a few changes to get the tests to run faster (e.g., instead of `Zucker` that was fetching 9 pages or results, I switched it to `Cattani` that returns only 3 pages).

d. I changed the network request process to be aggressive and repeat continuously until getting back results. Perhaps a bit too aggressive.

The current code and tests work well. Sometimes seems to get stuck, with Tor not updating the IP address used to access Google Scholar. I do not know if we need to refresh the `_SESSION` object on the Python side, or there is a need to restart the Tor service when this happens.

@silvavn and @bielsnohr please take a look. If you agree, we can merge that and use the GitHub Actions workflow as our sanity check that whatever we do does not introduce breaking changes.

Then, we can start working on merging the remaining "minor" pull requests that add features and fix bugs. 

Once we catch up, it will be time to start working on https://github.com/OrganicIrradiation/scholarly/pull/76

**Comment by ipeirotis** [comment]
I think we are getting into decent shape. 

Most issues are now resolved.

There are two bugs (confirmed)
https://github.com/OrganicIrradiation/scholarly/issues/63
and
https://github.com/OrganicIrradiation/scholarly/issues/61

The remaining issues are requests for additional features, not anything that is broken.

The three remaining PRs are also additional features, which we should incorporate. Of course, with the new code base, the PRs are not directly usable, but the code that they submitted should be possible to use without a lot of modifications.

For upcoming/desired work, I started creating issues, so that we have a clear list of things to work on.

With the current pace, I think we should be able to get this package out of "Alpha" and release a "1.0" version within the next couple of weeks.

**Comment by ipeirotis** [comment]
I have closed the last two stale PRs that added new functionality, as the codebase has changed significantly. 

I transferred these PRs to issues so that we can track them. 

I am closing this issue for now, as all past PRs have been handled one way or another.
