### ISSUE TITLE
Improvements to test suite

### ISSUE THREAD

**Issue by bielsnohr** [OrganicIrradiation/scholarly#84]
It has been a perennial problem for scholarly that the data used for tests is constantly changing, meaning tests fail not because there is an error in the code, but because the static test numbers are out of date with what Google Scholar returns. The current solution is #82 (which copies from #60).

Longer term, it would be nice to have a static set of pages that return constant data for each test, as mentioned in https://github.com/OrganicIrradiation/scholarly/issues/77#issuecomment-626346248 .

Of course, this has its own downside in that the static page will also become out of date with Google Scholar. A hybrid approach will likely be best. Thoughts welcome.

**Comment by ipeirotis** [comment]
I do not like the idea of relying *just* on static web pages for tests. We can definitely expand the current tests to run against a static set of pages, but testing the live functionality is important. 

Perhaps the use of proxies should be embedded in the library directly, together with retries and resets if the connection fails, or if there is a captcha.

**Comment by ipeirotis** [comment]
I tried to fix these issues at https://github.com/OrganicIrradiation/scholarly/pull/88

Now the library is very persistent in submitting network calls, until success. Perhaps we want to issue a "max retries" limit, as now the test suite gets sometimes stuck in with infinite retries, instead of refreshing the underlying proxy.
